tu_mascota/apps/posts/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.list_pet_posts, name='list_pet_posts'),
    path('pet/add/', views.add_pet_post, name='add_pet_post'),
    re_path(r'pet/(?P<pet_id>\d+)/$', views.pet_post_detail, name='pet_post_detail'),
    re_path(r'pet/(?P<pet_id>\d+)/edit/$', views.edit_pet_post, name='edit_pet_post'),
]

tu_mascota/tu_mascota/urls.py
from django.contrib import admin
from django.contrib.auth import logout, views as auth_views
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.static import serve
from .views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/',  logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

tu_mascota/apps/posts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .behaviors import Descriptable, Timestampable, Localizable
from authentication.models import User
# Create your models here.


DONATION_STATUS = (
    ('donated', _('Donado')),
    ('available', _('Disponible'))
)

STATUS = (
    ('missing', _('Perdido')),
    ('finded', _('Encontrado'))
)

AGE = (
    ('puppy', _('Cachorro')),
    ('young', _('Joven')),
    ('adult', _('Adulto'))
)

SIZE = (
    ('small', _('Chico')),
    ('medium', _('Mediano')),
    ('large', _('Grande'))
)

SEX = (
    ('female', _('Hembra')),
    ('male', _('Macho'))
)

PET = (
    ('dog', _('Perro')),
    ('cat', _('Gato')),
    ('other', _('Otros')),
    ('capi', _('Carpincho'))
)


class Pet(Descriptable, Timestampable, Localizable, models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='publications')
    status = models.CharField(_('Estado'), max_length=80, choices=STATUS)
    type = models.CharField(_('Tipo de mascota'), max_length=80, choices=PET)
    age_estimation = models.CharField(_('Edad aproximada'), choices=AGE, max_length=20)
    sex = models.CharField(_('Sexo'), choices=SEX, max_length=80)
    size = models.CharField(_('Tamaño'), choices=SIZE, max_length=20)
    color = models.CharField(_('Color'), max_length=40)
    hair = models.CharField(_('Pelaje'), max_length=40)

    def __str__(self):
        return f'{self.type}, {self.status}, {self.location}'


class PetImage(models.Model):
    image = models.ImageField(_('Imagen'), upload_to='posts/images/pets/')
    post = models.ForeignKey(Pet, on_delete=models.CASCADE, related_name='pet_images')

    def __str__(self):
        return f'pet image of {self.post}'


class Donation(Descriptable, Timestampable, Localizable, models.Model):
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='donation_publications')
    status = models.CharField(_('Estado'), max_length=20, choices=DONATION_STATUS)

    def __str__(self):
        return f'{self.status}, {self.location}'

class DonationImage(models.Model):
    image = models.ImageField(_('Imagen'), upload_to='posts/images/donations/')
    post = models.ForeignKey(Donation, on_delete=models.CASCADE, related_name='donation_images')

    def __str__(self):
        return f'donation image of {self.post}'

tu_mascota/templates/add_pet_post.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block extra_css %}
    <link href="{% static 'css/smartWizard/smart_wizard.css'%}"  rel="stylesheet" type="text/css" />
    <link href="{% static 'css/smartWizard/smart_wizard_theme_arrows.css'%}"  rel="stylesheet" type="text/css" />
    <link href="{% static 'css/smartWizard/smart_wizard_theme_dots.css'%}"  rel="stylesheet" type="text/css" />
    <link href="{% static 'css/add_pet_post.css'%}"  rel="stylesheet" type="text/css" />
{% endblock %}
{% block content %}
<div class="row">
    <div class="text-left col-md-12 col-xl-12 col-lg-12 ">&nbsp; &nbsp; &nbsp;
        <div>
          <legend> Añadir nueva publicación </legend>
        </div>
        <div id='wizard-main-container' class="col-md-10 col-sm-12 offset-md-1">
            <div class="w-100">
              <form id="add_pet_post_form" action="{% url 'posts:add_pet_post' %}" method="POST"  enctype="multipart/form-data">
                {% csrf_token %}
                <div id="smartwizard" class="col-md-12 sw-theme-dots">
                    <ul>
                      <li><a href="#step-1">Estado y ubicación <br /></a></li>
                      <li><a href="#step-2">Datos del animal<br /></a></li>
                      <li><a href="#step-3">Informacion extra<br /></a></li>
                      <li><a href="#step-4">Adjuntar imagenes<br /></a></li>
                    </ul>

                    <div id="wizard-container" class="col-12">
                      <div id="step-1" class="col-md-12">
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <div class='form-group'>
                                <label> {{ pet_form.status.label }} </label>
                                {% render_field pet_form.status class="form-control"  %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.location.label }} </label>
                                {% render_field pet_form.location class="form-control"  %}
                            </div>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <div class='form-group'>
                                <label> {{ pet_form.neighborhood.label }} </label>
                                {% render_field pet_form.neighborhood class="form-control"  %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.state.label }} </label>
                                {% render_field pet_form.state class="form-control"  %}
                            </div>
                          </div>
                        </div>
                      </div>
                      <div id="step-2" class="col-md-12">
                        <div class="row">
                          <div class="col-md-6 col-sm-12">
                            <div class='form-group'>
                                <label> {{ pet_form.type.label }} </label>
                                {% render_field pet_form.type class="form-control" %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.age_estimation.label }} </label>
                                {% render_field pet_form.age_estimation class="form-control" %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.sex.label }} </label>
                                {% render_field pet_form.sex  class="form-control"%}
                            </div>
                          </div>
                          <div class="col-md-6 col-sm-12">
                            <div class='form-group'>
                                <label> {{ pet_form.color.label }} </label>
                                {% render_field pet_form.color class="form-control" %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.size.label }} </label>
                                {% render_field pet_form.size class="form-control" %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.hair.label }} </label>
                                {% render_field pet_form.hair class="form-control"  %}
                            </div>
                          </div>
                        </div>
                      </div>
                      <div id="step-3" class="">
                        <div class="row">
                          <div class="col-md-10 col-sm-12 offset-md-1">
                            <div class='form-group'>
                                <label> {{ pet_form.short_description.label }} </label>
                                {% render_field pet_form.short_description class="form-control"  %}
                            </div>
                            <div class='form-group'>
                                <label> {{ pet_form.full_description.label }} </label>
                                {% render_field pet_form.full_description class="form-control" %}
                            </div>
                          </div>
                        </div>
                      </div>
                      <div id="step-4" class="">
                          {{pet_images_formset.management_form}}
                          <div id="pet_image_form-container">
                            <div class="row offset-md-1">
                            {% for pet_image_form in pet_images_formset %}
                              <div class='form-group col-md-5 col-sm-12 image-label'>
                                <label class="pet-image-handler" for="{{pet_image_form.image.auto_id}}">
                                  <figure>

                                    <img class='pet-image-display' id="img-{{pet_image_form.auto_id}}" src='{% static "img/add_image_placeholder.png" %}' />
                                    {% render_field pet_image_form.image class="form-control d-none pet-image-input" %}
                                  </figure>
                                </label>
                              </div>
                            {% endfor %}
                            </div>
                          </div>
                      </div>
                    </div>
                </div>
              </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
    <script type='text/javascript' src='{% static "js/smartWizard/smartWizard.js"%}'></script>
    <script type='text/javascript'>
			var btnFinish = $('<button></button>').text('Publicar')
        .addClass('btn btn-success')
        .on('click', function(){ $('#add_pet_post_form').submit()});

      $(document).ready(function(){
        $('#smartwizard').smartWizard({
          lang: {next: 'Siguiente', previous: 'Anterior'},
          toolbarSettings: {
            toolbarExtraButtons: [btnFinish]
          }
        });
      });
    </script>
    <script type='text/javascript'>
      function displayImg(source, display){
        if (source.files && source.files[0]) {
          let reader = new FileReader();
          reader.onload = (e) => {
            $(display)
              .attr('src', e.target.result);
          }
          reader.readAsDataURL(source.files[0]);
        }
      }

      $(document).ready(function(){
        $('input.pet-image-input').on('change', function(event){
          let source = event.currentTarget;
          let display = event.currentTarget.previousElementSibling;
          displayImg(source, display);
        })
      })
    </script>
{% endblock %}

tu_mascota/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        {% block title %} <title>Blank Template for Bootstrap</title> {% endblock %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'css/fontAwesome/css/all.min.css'%}"  rel="stylesheet" type="text/css" />
        <!-- Custom styles for this template -->
        {% block extra_css %} {% endblock %}
    </head>
    <body>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <nav class="navbar navbar-expand-lg fixed-top navbar-bg navbar-dark">
            <a class="navbar-brand" href="#">
                <img src="{% static 'img/LOGO.png' %}" width="48px" height="48px">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto lead font-weight-bold">
                    <li class="nav-item">
                      <a class="nav-link active" href="{% url 'posts:list_pet_posts'%}">Encontra a tu mascota</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts:add_pet_post' %}">Publicar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Donaciones!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#footer">Conócenos</a>
                    </li>
                </ul>
                <form class="form-inline">
                    <div class="dropdown">
                        {% if request.user.is_authenticated %}
                        <a class="btn dropdown-toggle btn-light d-inline font-weight-bold" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user"></i> {{request.user.username}}
</a>
                        <div class="dropdown-menu text-left dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <a href="#" class="dropdown-item">Ver Perfil</a>
                            <a class="dropdown-item" href="#">Mis Publicaciones</a>
                            <a class="dropdown-item" href="/logout">Salir</a>
                        </div>
                        {% else %}
                        <a class="btn btn-outline-warning d-inline" href="/login/" ><i class="fas fa-sign-in-alt"></i> Iniciar sesión</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </nav>
        <div class="container col-11 mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 pt-5 pt-sm-5 pt-md-5 pt-lg-5 pt-xl-5 ">
        {% block content %}
        {% endblock %}
        </div>
        <footer id='footer' class="col-12 text-center">
            <section id='inFooter'>
            <h1>Sobre Nosotros</h1>
                <div class="col-8 offset-2 text-center">

                <p>Este proyecto tiene como objetivo ayudar a que los usuarios localicen sus mascotas extraviadas y a que las mascotas que se hallan perdidas puedan reencontrarse con sus dueños.</p>

                <p>Partimos del problema que hay cuando se pierde o encuentra un animal, por lo general utilizamos redes sociales para encontrarlos, pero la información se pierde entre publicaciónes y esta dispersa en la web.</p>

                <p>Con este sistema se podría unificar los focos para encontrarse con su mascota rapidamente, ya que permite utilizar filtros de busqueda por tipo de animal, zona en que fue encontrado o se perdio, color, tamaño, sexo entre otros.</p> 

                </div>

            </section>
	    <p id='copy-rights'>&copy; Copyright 2019 | CanMoBit</p>
        </footer>
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% block extra_js %} {% endblock %}
    </body>
</html>

tu_mascota/templates/conocenos.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Blank Template for Bootstrap</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="style.css" rel="stylesheet">
    </head>
    <body>
        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <nav class="navbar navbar-expand-lg fixed-top bg-info navbar-dark">
            <a class="navbar-brand" href="#">
                <img src="1%20LOGO.png" width="48px" height="48px">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto lead font-weight-bold">
                    <li class="nav-item">
                        <a class="nav-link active" href="/publications.html">Encontra a tu mascota</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Buscamos hogar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Donaciones!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Conócenos</a>
                    </li>
                </ul>
                <form class="form-inline">
                    <div class="dropdown">
                        <button class="btn dropdown-toggle btn-light d-inline font-weight-bold" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Usuario
</button>
                        <div class="dropdown-menu text-left dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                            <a href="#" class="dropdown-item">Ver Perfil</a>
                            <a class="dropdown-item" href="#">Mis Publicaciones</a>
                            <a class="dropdown-item" href="#">Salir</a>
                        </div>
                    </div>
                </form>
            </div>
        </nav>
        <div class="container w-75 mt-5 mt-sm-5 mt-md-5 mt-lg-5 mt-xl-5 pt-5 pt-sm-5 pt-md-5 pt-lg-5 pt-xl-5 ">
            <section class="text-center">
                <h1 class="text-center">Sobre nosotros&nbsp;</h1>
                <p class="text-center"><p><p>Este proyecto tiene como objetivo ayudar a que los usuarios localicen sus mascotas extraviadas y a que las mascotas que se hallan perdidas puedan reencontrarse con sus dueños.<br></p><p>Partimos del problema que hay cuando se pierde o encuentra un animal, por lo general utilizamos redes sociales para encontrarlos, pero la información se pierde entre publicaciónes y esta dispersa en la web.</p><p>Con este sistema se podría unificar los focos para encontrarse con su mascota rapidamente, ya que permite utilizar filtros de busqueda por tipo de animal, zona en que fue encontrado o se perdio, color, tamaño, sexo entre otros.</p><p>Cada publicación irá acompañada de una foto que permita identificar facilmente al animal en cuestion.</p><p>También se podrá utilizar para que las personas compartan artículos para mascotas que ya no utilicen y asi otras personas&nbsp;<span style="font-size: 1rem;">reutilizarlos.</span></p></p></p>
            </section>
        </div>
        <footer class="pg-empty-placeholder"></footer>
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/popper.js"></script>
        <script src="bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

tu_mascota/templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="pb-3 col-md-6 offset-md-3 col-xl-6 offset-xl-3 col-lg-6 offset-lg-3 ">&nbsp; &nbsp; &nbsp;
      <div class="text-center">  
        <h1>¡Bienvenido!</h1><br>
      </div>
        <form action="/login/" method="POST" >
        {% csrf_token %}
          <div class="field-container col">
            <label for="{{form.username.auto_id}}">{{form.username.label}}</label><br>
            {% render_field form.username class="form-control" %}
            {{form.username.errors}}
          </div>
          <div class="field-container col">
            <label for="{{form.password.auto_id}}">{{form.password.label}}</label><br>
            {% render_field form.password class="form-control" type="password" %}
            {{form.password.errors}}
          </div>
          <div class="field-container text-center">
            <input  class="btn btn-success" type="submit" value="Iniciar Sesión">
          </div>
          <div class="text-center">
            <a href="/register"> ¿No eres usuario?, Registrate!</a>
          </div>
        </form>
    </div>
</div>
{% endblock %}

tu_mascota/templates/pet_post_detail.html
{% extends 'base.html' %}
{% load static thumbnail %}
{% block content %}
<div class="row">
    <div class="text-left col-md-6 col-xl-6 col-lg-6 ">&nbsp; &nbsp; &nbsp;
        <div id="carousel1" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel1" data-slide-to="0" class="active"></li>
                <li data-target="#carousel1" data-slide-to="1"></li>
                <li data-target="#carousel1" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              {% for image in pet_post.pet_images.all %}
	      {% thumbnail image.image "850x520" crop="center" as img %}
                <div class="carousel-item {% if forloop.first %} active {% endif %}">
                  <img class="d-block w-100" src="{{img.url}}" alt="slide-{{forloop.counter}}" height="100%" width="100%">
                </div>
	      {% endthumbnail %}
              {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
            <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
        </div>
        <div class="row mt-2 mt-sm-2 mt-md-2 mt-lg-2 mt-xl-2 pt-xl-3 pt-lg-3 pt-md-3 pt-sm-3 pt-3 pl-xl-4 pl-lg-4 pl-md-4 pl-sm-4 pl-4">
            <div class="w-100">
              {% with pet_post.created_by as user %}  
              <details>
                    <summary class="d-block text-left">
                        <h3 class="text-right d-inline-flex">
                          Información de Contacto</h3>
                    </summary>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <td>{{user.first_name}}</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">Telefono</th>
                                <td>{{user.telephone}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Correo Electronico</th>
                                <td>{{user.email}}</td>
                            </tr>
                            <tr>
                                <th scope="row">Dirección</th>
                                <td>{{user.address}}</td>
                            </tr>
                        </tbody>
                    </table>
                </details>
                {% endwith %}
            </div>
        </div>
    </div>
    <div class="text-left col-md-6 ">
        <div class="row">
            <h3 class="ml-2 ml-sm-2 ml-md-2 ml-lg-2 pl-lg-1 ml-xl-2">Datos</h3>
            <div class="col-md-12 ml-2 ml-sm-2 ml-md-2 ml-lg-2 ml-xl-2">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tipo</th>
                            <th>{{pet_post.get_type_display}}</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Sexo</th>
                            <td>{{pet_post.get_sex_display}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Edad</th>
                            <td>{{pet_post.get_age_estimation_display}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Lugar</th>
                            <td>{{pet_post.location}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Estado</th>
                            <td>{{pet_post.get_status_display}}</td>
                        </tr>
                    </tbody>
                </table>
                <h3>Rasgos</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Color</th>
                            <td>{{pet_post.color}}</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Pelaje</th>
                            <td>{{pet_post.hair}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Tamaño</th>
                            <td>{{pet_post.get_size_display}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Caracterisistiacas especiales&nbsp;</th>
                            <td>{{pet_post.short_description}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Otros</th>
                            <td>{{pet_post.full_description}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tu_mascota/templates/publications.html
{% extends "base.html" %}
{% load static thumbnail %}
{% block extra_css %}
    <link href="{% static 'css/publications.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="row filters-container col-12">
    {% for filter_label, filter_field, filter_dict in filters_dicts %}
    <div class='col-md-2'>
        <label for='filter-{{filter_field}}'> {{filter_label}} </label>
        <select id='filter-{{filter_field}}' class='form-control filter-select' data-filter_field={{filter_field}}>
            <option value='all'>Todos</option>
            {% for key, value in filter_dict %}
                <option value='{{key}}' {% if key in request.active_filters %} selected {% endif %}>{{value}}</option>
            {% endfor %}
        </select>
    </div>
    {% endfor %}
</div>
<div class="row posts-container mb-lg-5 mb-sm-5 mb-5 mb-md-5 mb-xl-5">
  {% for obj in objs %}
    <div class="col-md-3 post-container">
	{% thumbnail obj.pet_images.first.image '350x300' crop='center' as img %}
      <img src="{{img.url}}" width="100%">
      {% endthumbnail %}
      <span><strong>{{obj.get_type_display}} {{obj.get_sex_display}}</strong></span>
      <span><strong>{{obj.get_status_display}}</strong></span>
      <p> <small>{{obj.creation_date}}</small> <br> <small>{{obj.location}}</small> </p>
      <a name="anchor" class="btn btn-primary text-right float-right" href="{% url 'posts:pet_post_detail' pet_id=obj.pk %}">Ver mas</a>
    </div>
    {% empty %}
    <div class="col-md-8 text-center">
      <h2> No hay publicaciones </h2>
    </div>
  {% endfor %}
</div>
<div class="row text-center d-flex justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}
{% block extra_js %}
    <script type='text/javascript'>

        function filterQueryString(field, value){
            let current = window.location.search;
            let queryString = new URLSearchParams(current);
            if (queryString.has(field)){
                queryString.delete(field);
            }
            queryString.append(field, value);
            return queryString.toString();
        }

        $(document).ready(function(){
            pet_active_filters = localStorage;
            $('select.filter-select').on('change', function(event){
                let filter = event.currentTarget;
                let field = filter.getAttribute('data-filter_field');
                let value = filter.value;
                pet_active_filters.setItem(field, value);
                window.location.search = filterQueryString(field, value);
            });
        })

    </script>
{% endblock %}